version: "3"
services:
  app:
    hostname: app
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"